artifact_location: file:///C:\Users\praka\Acads\M_Tech\new_git_test\test-repo-v2\src/mlflow_tracking/0
creation_time: 1723022782656
experiment_id: '0'
last_update_time: 1723022782656
lifecycle_stage: active
name: Default
