artifact_location: file:///C:\Users\praka\Acads\M_Tech\new_git_test\test-repo-v2\src/mlflow_tracking/973038815847846131
creation_time: 1723022782665
experiment_id: '973038815847846131'
last_update_time: 1723022782665
lifecycle_stage: active
name: mnist_cnn_experiment_v2
